name: Deploy Branches to FTP

on:
  push:
    branches:
      - main
      - dev
      - nileshbiniwale
      - mayureshashrit
      - pradipsalke

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Branch Name
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set Deploy Path
        run: |
          echo "DEPLOY_DIR=/${BRANCH_NAME}/" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_BASE_PATH=/${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: ${{ env.NEXT_PUBLIC_BASE_PATH }}

      - name: Verify Build
        run: ls -la out

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: ./pradipsalke/
          protocol: ftp
          security: loose